version: '2'
services:
    my-irc:
        build: .
        restart: always
        volumes:
            - ./src:/src
        environment:
            - VIRTUAL_HOST=$IRC_HOST
    reverse-proxy:
        image: jwilder/nginx-proxy
        restart: always
        ports:
            - $PROXY_HTTP_PORT:80/tcp
            - $PROXY_HTTPS_PORT:443/tcp
        volumes:
            - $DOCKER_SOCK:/tmp/docker.sock:ro