version: "3"
services:
  my-irc:
    container_name: my-irc
    image: lereverandnox/my_irc
    environment:
      - GIPHY_API_KEY=$GIPHY_API_KEY
      - GIPHY_BASE_URL=$GIPHY_BASE_URL
      - APPLICATION_ENV=$APPLICATION_ENV
