version: "3"
services:
  my-irc:
    build: ./
    volumes:
      - $IRC_SRC:/src
    environment:
      - VIRTUAL_HOST=$IRC_HOST
      - VIRTUAL_PORT=80
    entrypoint: ["npm", "run", "dev"]
  reverse-proxy:
    image: jwilder/nginx-proxy
    ports:
      - $HTTP_PORT:80/tcp
      - $HTTPS_PORT:443/tcp
    volumes:
      - $DOCKER_SOCK:/tmp/docker.sock:ro
